<?php
// Language translations
$translations = [
    'en' => [
        // General
        'site_name' => 'Wedding Planner',
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'login' => 'Login',
        'logout' => 'Logout',
        'signup' => 'Sign Up',
        'cart' => 'Cart',
        'close' => 'Close',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'delete' => 'Delete',
        'edit' => 'Edit',
        'add' => 'Add',
        'remove' => 'Remove',
        'actions' => 'Actions',
        'yes' => 'Yes',
        'no' => 'No',
        
        // Hero Page
        'hero_badge' => 'Smart Wedding Planning',
        'hero_title' => 'Forever Begins Here',
        'hero_subtitle' => 'Plan your dream wedding with elegance and ease',
        'hero_description' => 'From stunning venues to exquisite catering, professional photography to beautiful decorations — we bring together everything you need to create the perfect celebration of your love story.',
        'hero_feature_1' => 'Curated Vendors',
        'hero_feature_2' => 'Custom Packages',
        'hero_feature_3' => 'Easy Booking',
        'start_planning' => 'Start Planning',
        'explore_services' => 'Explore Services',
        'happy_couples' => 'Happy Couples',
        'premium_venues' => 'Premium Venues',
        'trusted_vendors' => 'Trusted Vendors',
        'customer_rating' => 'Customer Rating',
        
        // Services Section
        'our_services' => 'Our Services',
        'services_title' => 'Everything for Your Special Day',
        'services_description' => 'We offer a complete range of wedding services to make your celebration unforgettable',
        'service_venues' => 'Elegant Venues',
        'service_venues_desc' => 'Choose from our collection of stunning halls and outdoor spaces perfect for your ceremony and reception.',
        'service_catering' => 'Gourmet Catering',
        'service_catering_desc' => 'Delight your guests with exquisite menus crafted by top chefs, from elegant buffets to plated dinners.',
        'service_photo' => 'Photography & Video',
        'service_photo_desc' => 'Capture every precious moment with our professional photographers and videographers.',
        'service_decor' => 'Décor & Florals',
        'service_decor_desc' => 'Transform your venue with stunning decorations and beautiful floral arrangements.',
        'service_entertainment' => 'Entertainment',
        'service_entertainment_desc' => 'From live bands to DJs, we\'ll help you create the perfect atmosphere.',
        'service_print' => 'Invitations & Stationery',
        'service_print_desc' => 'Custom invitations and stationery that match your wedding theme perfectly.',
        
        // CTA Section
        'ready_to_begin' => 'Ready to Begin?',
        'cta_subtitle' => 'Join hundreds of happy couples who trusted us with their special day',
        'create_account' => 'Create Account',
        'continue_guest' => 'Continue as Guest',
        'guest_mode' => 'Guest Mode',
        
        // Login/Signup
        'welcome_back' => 'Welcome Back',
        'login_subtitle' => 'Log in to continue planning',
        'email_address' => 'Email Address',
        'password' => 'Password',
        'create_password' => 'Create Password',
        'full_name' => 'Full Name',
        'create_new_account' => 'Create New Account',
        'already_have_account' => 'Already have an account?',
        'start_planning_subtitle' => 'Start planning your perfect day',
        'fill_all_fields' => 'Please fill all fields',
        'invalid_credentials' => 'Invalid credentials',
        'email_exists' => 'Email already exists',
        
        // Main Page
        'browse_packages' => 'Browse Packages',
        'welcome' => 'Welcome',
        'guest' => 'Guest',
        'browse_categories' => 'Browse each category and add what you need to your cart.',
        'add_to_cart' => 'Add to Cart',
        'add_bundle' => 'Add Bundle to Cart',
        'popular_bundles' => 'Popular Wedding Bundles',
        'bundles_desc' => 'Ready-made packages that combine halls, food, photography and more.',
        
        // Categories
        'cat_services' => 'Services',
        'cat_services_desc' => 'Essentials to welcome your guests and start the celebration.',
        'cat_decor' => 'Decor',
        'cat_decor_desc' => 'Styling and details to transform the hall into your dream venue.',
        'cat_food' => 'Food',
        'cat_food_desc' => 'Curated menus to delight every table.',
        'cat_photo' => 'Photo',
        'cat_video' => 'Video',
        'cat_photo_video_desc' => 'Capture every moment with professional coverage.',
        'cat_print' => 'Print',
        'cat_print_desc' => 'Invitations, table cards and more printed to match your theme.',
        'cat_default_desc' => 'Handpicked options for your wedding day.',
        
        // Cart
        'your_cart' => 'Your Cart',
        'cart_empty' => 'Your cart is empty',
        'total' => 'Total',
        'place_order' => 'Place Order',
        'your_name' => 'Your name',
        'your_email' => 'Your email',
        'order_success' => 'Your order was placed successfully.',
        'order_empty' => 'Your cart is empty.',
        'guest_order_error' => 'Guests cannot place orders.',
        'please_login' => 'Please',
        'or' => 'or',
        'to_place_orders' => 'to place orders.',
        
        // My Orders
        'my_orders' => 'My Orders',
        'order_history' => 'View your order history and details',
        'order' => 'Order',
        'order_date' => 'Date',
        'completed' => 'Completed',
        'qty' => 'Qty',
        'no_orders' => 'No orders yet',
        'no_orders_desc' => 'You haven\'t placed any orders yet. Start planning your perfect wedding!',
        'browse_services' => 'Browse Services',
        
        // Dashboard
        'overview' => 'Overview',
        'users' => 'Users',
        'admins' => 'Admins',
        'super_admins' => 'Super Admins',
        'services' => 'Services',
        'bundles' => 'Bundles',
        'orders' => 'Orders',
        'revenue' => 'Revenue',
        'recent_orders' => 'Recent Orders',
        'id' => 'ID',
        'name' => 'Name',
        'email' => 'Email',
        'username' => 'Username',
        'you' => 'You',
        'date' => 'Date',
        'no_orders_yet' => 'No orders yet',
        
        // Manage Items
        'manage_items' => 'Manage Items',
        'manage_users' => 'Manage Users',
        'user_management' => 'User Management',
        'all_users' => 'All Users',
        'promote_to_admin' => 'Promote to Admin',
        'demote_to_user' => 'Demote to User',
        'delete_user' => 'Delete User',
        'role' => 'Role',
        'created' => 'Created',
        'super_admin_role' => 'Super Admin',
        'admin_role' => 'Admin',
        'user_role' => 'User',
        'cannot_delete_last_superadmin' => 'Cannot delete the last super admin',
        'user_deleted' => 'User deleted successfully',
        'user_promoted' => 'User promoted to admin',
        'user_demoted' => 'User demoted to regular user',
        'confirm_delete_user' => 'Are you sure you want to delete this user?',
        'you_cannot_modify_yourself' => 'You cannot modify your own role',
        'manage_items_desc' => 'Add, edit, or remove services and bundles',
        'add_new_item' => 'Add New Item',
        'edit_item' => 'Edit Item',
        'title' => 'Title',
        'price' => 'Price',
        'category' => 'Category',
        'icon' => 'Icon',
        'select_category' => 'Select category...',
        'is_bundle' => 'Is Bundle?',
        'item_added' => 'Item added successfully',
        'item_updated' => 'Item updated successfully',
        'item_deleted' => 'Item deleted successfully',
        'select_icon' => 'Select an icon',
        
        // Theme
        'bride' => 'Bride',
        'groom' => 'Groom',
        'copyright' => '© 2024 Wedding Planner. Making dreams come true.',
    ],
    
    'ar' => [
        // General
        'site_name' => 'مخطط الزفاف',
        'home' => 'الرئيسية',
        'dashboard' => 'لوحة التحكم',
        'login' => 'تسجيل الدخول',
        'logout' => 'تسجيل الخروج',
        'signup' => 'إنشاء حساب',
        'cart' => 'السلة',
        'close' => 'إغلاق',
        'save' => 'حفظ',
        'cancel' => 'إلغاء',
        'delete' => 'حذف',
        'edit' => 'تعديل',
        'add' => 'إضافة',
        'remove' => 'إزالة',
        'actions' => 'الإجراءات',
        'yes' => 'نعم',
        'no' => 'لا',
        
        // Hero Page
        'hero_badge' => 'تخطيط ذكي لحفلات الزفاف',
        'hero_title' => 'الأبدية تبدأ هنا',
        'hero_subtitle' => 'خطط لزفاف أحلامك بأناقة وسهولة',
        'hero_description' => 'من القاعات المذهلة إلى الضيافة الفاخرة، والتصوير الاحترافي إلى الديكورات الجميلة — نجمع لك كل ما تحتاجه لإنشاء احتفال مثالي بقصة حبك.',
        'hero_feature_1' => 'موردون مختارون',
        'hero_feature_2' => 'باقات مخصصة',
        'hero_feature_3' => 'حجز سهل',
        'start_planning' => 'ابدأ التخطيط',
        'explore_services' => 'استكشف الخدمات',
        'happy_couples' => 'أزواج سعداء',
        'premium_venues' => 'قاعات فاخرة',
        'trusted_vendors' => 'موردون موثوقون',
        'customer_rating' => 'تقييم العملاء',
        
        // Services Section
        'our_services' => 'خدماتنا',
        'services_title' => 'كل شيء ليومك المميز',
        'services_description' => 'نقدم مجموعة كاملة من خدمات الزفاف لجعل احتفالك لا يُنسى',
        'service_venues' => 'قاعات أنيقة',
        'service_venues_desc' => 'اختر من مجموعتنا من القاعات الرائعة والمساحات الخارجية المثالية لحفلك.',
        'service_catering' => 'ضيافة فاخرة',
        'service_catering_desc' => 'أسعد ضيوفك بقوائم طعام راقية من أفضل الطهاة.',
        'service_photo' => 'التصوير والفيديو',
        'service_photo_desc' => 'التقط كل لحظة ثمينة مع مصورينا المحترفين.',
        'service_decor' => 'الديكور والزهور',
        'service_decor_desc' => 'حوّل قاعتك بديكورات مذهلة وتنسيقات زهور جميلة.',
        'service_entertainment' => 'الترفيه',
        'service_entertainment_desc' => 'من الفرق الموسيقية إلى منسقي الأغاني، سنساعدك على خلق الأجواء المثالية.',
        'service_print' => 'الدعوات والمطبوعات',
        'service_print_desc' => 'دعوات وبطاقات مخصصة تتناسب مع ثيم حفل زفافك.',
        
        // CTA Section
        'ready_to_begin' => 'هل أنت مستعد للبدء؟',
        'cta_subtitle' => 'انضم إلى مئات الأزواج السعداء الذين وثقوا بنا في يومهم المميز',
        'create_account' => 'إنشاء حساب',
        'continue_guest' => 'متابعة كضيف',
        'guest_mode' => 'وضع الضيف',
        
        // Login/Signup
        'welcome_back' => 'مرحباً بعودتك',
        'login_subtitle' => 'سجل دخولك لمتابعة التخطيط',
        'email_address' => 'البريد الإلكتروني',
        'password' => 'كلمة المرور',
        'create_password' => 'إنشاء كلمة مرور',
        'full_name' => 'الاسم الكامل',
        'create_new_account' => 'إنشاء حساب جديد',
        'already_have_account' => 'لديك حساب بالفعل؟',
        'start_planning_subtitle' => 'ابدأ التخطيط ليومك المثالي',
        'fill_all_fields' => 'يرجى ملء جميع الحقول',
        'invalid_credentials' => 'بيانات الدخول غير صحيحة',
        'email_exists' => 'البريد الإلكتروني موجود بالفعل',
        
        // Main Page
        'browse_packages' => 'تصفح الباقات',
        'welcome' => 'مرحباً',
        'guest' => 'ضيف',
        'browse_categories' => 'تصفح كل فئة وأضف ما تحتاجه إلى سلتك.',
        'add_to_cart' => 'أضف إلى السلة',
        'add_bundle' => 'أضف الباقة إلى السلة',
        'popular_bundles' => 'باقات الزفاف الشائعة',
        'bundles_desc' => 'باقات جاهزة تجمع القاعات والطعام والتصوير والمزيد.',
        
        // Categories
        'cat_services' => 'الخدمات',
        'cat_services_desc' => 'الأساسيات لاستقبال ضيوفك وبدء الاحتفال.',
        'cat_decor' => 'الديكور',
        'cat_decor_desc' => 'التنسيق والتفاصيل لتحويل القاعة إلى مكانك المثالي.',
        'cat_food' => 'الطعام',
        'cat_food_desc' => 'قوائم طعام مختارة لإسعاد كل طاولة.',
        'cat_photo' => 'التصوير',
        'cat_video' => 'الفيديو',
        'cat_photo_video_desc' => 'التقط كل لحظة بتغطية احترافية.',
        'cat_print' => 'المطبوعات',
        'cat_print_desc' => 'دعوات وبطاقات الطاولات والمزيد مطبوعة لتتناسب مع الثيم.',
        'cat_default_desc' => 'خيارات مختارة بعناية ليوم زفافك.',
        
        // Cart
        'your_cart' => 'سلتك',
        'cart_empty' => 'سلتك فارغة',
        'total' => 'المجموع',
        'place_order' => 'إتمام الطلب',
        'your_name' => 'اسمك',
        'your_email' => 'بريدك الإلكتروني',
        'order_success' => 'تم إتمام طلبك بنجاح.',
        'order_empty' => 'سلتك فارغة.',
        'guest_order_error' => 'لا يمكن للضيوف إتمام الطلبات.',
        'please_login' => 'يرجى',
        'or' => 'أو',
        'to_place_orders' => 'لإتمام الطلبات.',
        
        // My Orders
        'my_orders' => 'طلباتي',
        'order_history' => 'عرض سجل طلباتك والتفاصيل',
        'order' => 'الطلب',
        'order_date' => 'التاريخ',
        'completed' => 'مكتمل',
        'qty' => 'الكمية',
        'no_orders' => 'لا توجد طلبات بعد',
        'no_orders_desc' => 'لم تقم بأي طلبات بعد. ابدأ في التخطيط لزفافك المثالي!',
        'browse_services' => 'تصفح الخدمات',
        
        // Dashboard
        'overview' => 'نظرة عامة',
        'users' => 'المستخدمون',
        'admins' => 'المسؤولون',
        'super_admins' => 'المسؤولون الرئيسيون',
        'services' => 'الخدمات',
        'bundles' => 'الباقات',
        'orders' => 'الطلبات',
        'revenue' => 'الإيرادات',
        'recent_orders' => 'الطلبات الأخيرة',
        'id' => 'المعرف',
        'name' => 'الاسم',
        'email' => 'البريد',
        'username' => 'اسم المستخدم',
        'you' => 'أنت',
        'date' => 'التاريخ',
        'no_orders_yet' => 'لا توجد طلبات بعد',
        
        // Manage Items
        'manage_items' => 'إدارة العناصر',
        'manage_users' => 'إدارة المستخدمين',
        'user_management' => 'إدارة المستخدمين',
        'all_users' => 'جميع المستخدمين',
        'promote_to_admin' => 'ترقية إلى مسؤول',
        'demote_to_user' => 'تخفيض إلى مستخدم',
        'delete_user' => 'حذف المستخدم',
        'role' => 'الدور',
        'created' => 'تاريخ الإنشاء',
        'super_admin_role' => 'مسؤول رئيسي',
        'admin_role' => 'مسؤول',
        'user_role' => 'مستخدم',
        'cannot_delete_last_superadmin' => 'لا يمكن حذف المسؤول الرئيسي الأخير',
        'user_deleted' => 'تم حذف المستخدم بنجاح',
        'user_promoted' => 'تمت ترقية المستخدم إلى مسؤول',
        'user_demoted' => 'تم تخفيض المستخدم إلى مستخدم عادي',
        'confirm_delete_user' => 'هل أنت متأكد من حذف هذا المستخدم؟',
        'you_cannot_modify_yourself' => 'لا يمكنك تعديل دورك الخاص',
        'manage_items_desc' => 'إضافة أو تعديل أو إزالة الخدمات والباقات',
        'add_new_item' => 'إضافة عنصر جديد',
        'edit_item' => 'تعديل العنصر',
        'title' => 'العنوان',
        'price' => 'السعر',
        'category' => 'الفئة',
        'icon' => 'الأيقونة',
        'select_category' => 'اختر الفئة...',
        'is_bundle' => 'هل هي باقة؟',
        'item_added' => 'تمت إضافة العنصر بنجاح',
        'item_updated' => 'تم تحديث العنصر بنجاح',
        'item_deleted' => 'تم حذف العنصر بنجاح',
        'select_icon' => 'اختر أيقونة',
        
        // Theme
        'bride' => 'العروس',
        'groom' => 'العريس',
        'copyright' => '© 2024 مخطط الزفاف. نحقق الأحلام.',
    ],

    // Kurdish Sorani (Central Kurdish)
    'ku' => [
        // General
        'site_name' => 'پلاندانانی شەهيان',
        'home' => 'ماڵەوە',
        'dashboard' => 'داشبۆرد',
        'login' => 'چوونەژوورەوە',
        'logout' => 'دەرچوون',
        'signup' => 'خۆت تۆماربکە',
        'cart' => 'سەبەتە',
        'close' => 'داخستن',
        'save' => 'پاشەکەوتکردن',
        'cancel' => 'هەڵوەشاندنەوە',
        'delete' => 'سڕینەوە',
        'edit' => 'دەستکاری',
        'add' => 'زیادکردن',
        'remove' => 'لابردن',
        'actions' => 'کردارەکان',
        'yes' => 'بەڵێ',
        'no' => 'نەخێر',
        
        // Hero Page
        'hero_badge' => 'پلاندانانی زیرەکانەی شەهيان',
        'hero_title' => 'هەموو شتێک لێرە دەست پێدەکات',
        'hero_subtitle' => 'شەهيانی خەونەکانت بە ئارام و جوانی پلاندانە',
        'hero_description' => 'لە هەڵبژاردنی قەڵا و هۆتێل و هۆل و خانۆکانەوە تا خزمەتگوزاری خۆراک، وێنەگرتن و ڤیدیۆ، ڕازاندنی شوێن و ڕازاندنی گەشت و هەموو دیکە وردەکارییە جوانەکان — هەمووی لە یەک شوێندایە بۆ شهيانێکی باشتر.',
        'hero_feature_1' => 'دابینکەری هەڵبژاردراو',
        'hero_feature_2' => 'پاکەتی تایبەتکراو',
        'hero_feature_3' => 'رێکخستنی ئاسان',
        'start_planning' => 'دەست بە پلاندانەوە بکە',
        'explore_services' => 'خزمەتگوزارییەکان ببینە',
        'happy_couples' => 'هاوسەرگیریی دڵخۆش',
        'premium_venues' => 'شوێنە بەرزەکان',
        'trusted_vendors' => 'دابینکەرە باوەکان',
        'customer_rating' => 'هەڵسەنگاندنی کڕیاران',
        
        // Services Section
        'our_services' => 'خزمەتگوزارییەکانمان',
        'services_title' => 'هەموو شتێک بۆ ڕۆژێکی تایبەت',
        'services_description' => 'پێکھاتەی تەواوی خزمەتگوزاریی زاوا بۆ شەهيانەکەت پێشکەش دەکەین بۆ ڕۆژێک نا بیناسراو.',
        'service_venues' => 'شوێنە جوانەکان',
        'service_venues_desc' => 'لە ناو قەڵا و هۆتێل و هۆل و بەرزترین شوێنەکان هەڵبژاردن بکە بۆ جەژنی شهيانەکەت.',
        'service_catering' => 'خۆاردنی بەرز',
        'service_catering_desc' => 'میوانەکانت بە خۆاردنی خۆشەویست و بەرز پلە خۆشحاڵ بکە؛ لە بوفە تا خواردنی خێزانەکان.',
        'service_photo' => 'وێنە و ڤیدیۆ',
        'service_photo_desc' => 'هەموو ساتێکی گرنگ بە وێنەگرتن و ڤیدیۆی پڕۆفیشناڵ بگرە.',
        'service_decor' => 'دیزاین و گول',
        'service_decor_desc' => 'شوێنەکە بگۆڕە بە هۆڵێکی خەونەکانت بە ڕوخسار و ڕازاندن و گولە جوانەکان.',
        'service_entertainment' => 'ئەنسامبل و میوزیک',
        'service_entertainment_desc' => 'لە دی‌جی تا بەرنامە ڕاستەوخۆ، هەموو شتێک بۆ فازێکی خۆش و جوان.',
        'service_print' => 'بانگهێشت و چاپکردن',
        'service_print_desc' => 'بانگهێشت، کارت و هەموو چاپەکان بە شێوەیەکی گونجاو لەگەڵ تەیمەکەت.',
        
        // CTA Section
        'ready_to_begin' => 'ئامادەیت بۆ دەست پێکردن؟',
        'cta_subtitle' => 'بەشداری لە سەدان هاوسەرگیریی دڵخۆش بکە کە شهيانەکانیان لە ئێمەوە ڕازاندووە',
        'create_account' => 'دروستکردنی هەژمار',
        'continue_guest' => 'بە میوان بەردەوام بە',
        'guest_mode' => 'دۆخی میوان',
        
        // Login/Signup
        'welcome_back' => 'بەخێربێیتەوە',
        'login_subtitle' => 'چوونەژوورەوە بۆ بەردەوام بوون لە پلاندانان',
        'email_address' => 'ناونیشانی ئیمەیڵ',
        'password' => 'وشەی نهێنی',
        'create_password' => 'وشەی نهێنی دروست بکە',
        'full_name' => 'ناوی تەواو',
        'create_new_account' => 'هەژماری نوێ دروست بکە',
        'already_have_account' => 'هەژمارت هەیە پێشتر؟',
        'start_planning_subtitle' => 'دەست بە پلاندانانی ڕۆژێکی خەونەکانت بکە',
        'fill_all_fields' => 'تکایە هەموو خانەکان پڕبکەوە',
        'invalid_credentials' => 'زانیاری نادروستە',
        'email_exists' => 'ئیمەیڵ پێشتر تۆمارکراوە',
        
        // Main Page
        'browse_packages' => 'پاکەتەکان ببینە',
        'welcome' => 'بۆخێربێیت',
        'guest' => 'میوان',
        'browse_categories' => 'هەر هاوپۆلێک ببینە و هەر ئەو شتانەی پێویستت بۆیە بۆ سەبەتەکەت زیاد بکە.',
        'add_to_cart' => 'زیادکردن بۆ سەبەتە',
        'add_bundle' => 'پاکەتەکە بۆ سەبەتە زیاد بکە',
        'popular_bundles' => 'پاکەتە باوەکانی شهيان',
        'bundles_desc' => 'پاکەتە ئامادەکراوەکان کە شوێن، خۆراک، وێنە و زیاتر پێکدەهێنن.',
        
        // Categories
        'cat_services' => 'خزمەتگوزارییەکان',
        'cat_services_desc' => 'خزمەتگوزاریی سەرەتایی بۆ پیشوازی لە میوانەکان و دەستپێکردنی جەژن.',
        'cat_decor' => 'دیزاین',
        'cat_decor_desc' => 'ستایڵ و وردەکاری بۆ گۆڕینی هۆڵەکەت بۆ شوێنێکی خەون.',
        'cat_food' => 'خۆراک',
        'cat_food_desc' => 'خوارنەوە و خۆراکی وەرزراو بۆ هەموو مێزێک.',
        'cat_photo' => 'وێنە',
        'cat_video' => 'ڤیدیۆ',
        'cat_photo_video_desc' => 'هەموو کاتێک بە وێنە و ڤیدیۆی پڕۆفیشناڵ تۆمار بکە.',
        'cat_print' => 'چاپکردن',
        'cat_print_desc' => 'بانگهێشت و کارت و چاپی دیکە بە گونجاوی تەیمەکەت.',
        'cat_default_desc' => 'هەڵبژاردنە وەرزراوەکان بۆ ڕۆژێکی هاوسەرگیری.',
        
        // Cart
        'your_cart' => 'سەبەتەکەت',
        'cart_empty' => 'سەبەتەکەت بەتاڵە',
        'total' => 'کۆی گشتی',
        'place_order' => 'داواکردن بنێرە',
        'your_name' => 'ناوت',
        'your_email' => 'ئیمەیڵەکەت',
        'order_success' => 'داواکارییەکەت بەسەرکەوتوویی تۆمار کرا.',
        'order_empty' => 'سەبەتەکەت بەتاڵە.',
        'guest_order_error' => 'میوان ناتوانێت داواکاری بنێرێت.',
        'please_login' => 'تکایە',
        'or' => 'یان',
        'to_place_orders' => 'بۆ ناردنی داواکاری.',
        
        // My Orders
        'my_orders' => 'داواکارییەکانم',
        'order_history' => 'مێژووی داواکاری و وردەکارییەکان ببینە',
        'order' => 'داواکاری',
        'order_date' => 'بەروار',
        'completed' => 'تەواو بووە',
        'qty' => 'ژمارە',
        'no_orders' => 'هێشتا هیچ داواکاریەت نەکردووە',
        'no_orders_desc' => 'هێشتا داواکاری نەکردووە. دەست بە پلاندانانی شهيانێکی خەونەکانت بکە!',
        'browse_services' => 'خزمەتگوزارییەکان ببینە',
        
        // Dashboard
        'overview' => 'کورتە',
        'users' => 'بەکارهێنەران',
        'admins' => 'بەڕێوەبەرەکان',
        'super_admins' => 'بەڕێوەبەری سەرەکی',
        'services' => 'خزمەتگوزاری',
        'bundles' => 'پاکەتەکان',
        'orders' => 'داواکارییەکان',
        'revenue' => 'داخڵکردن',
        'recent_orders' => 'دوایین داواکارییەکان',
        'id' => 'ناسنامە',
        'name' => 'ناو',
        'email' => 'ئیمەیڵ',
        'username' => 'ناوی بەکارهێنەر',
        'you' => 'تۆ',
        'date' => 'بەروار',
        'no_orders_yet' => 'هێشتا داواکاری نییە',
        
        // Manage Items
        'manage_items' => 'بەڕێوەبردنی شتان',
        'manage_users' => 'بەڕێوەبردنی بەکارهێنەران',
        'user_management' => 'بەڕێوەبردنی بەکارهێنەر',
        'all_users' => 'هەموو بەکارهێنەران',
        'promote_to_admin' => 'بیکەرە بە بەڕێوەبەر',
        'demote_to_user' => 'بیکە نرمال بە بەکارهێنەر',
        'delete_user' => 'بەکارهێنەر بسڕەوە',
        'role' => 'ڕۆڵ',
        'created' => 'دروستکراوە لە',
        'super_admin_role' => 'بەڕێوەبەری سەرەکی',
        'admin_role' => 'بەڕێوەبەر',
        'user_role' => 'بەکارهێنەر',
        'cannot_delete_last_superadmin' => 'ناتوانیت دواهەم بەڕێوەبەری سەرەکیت بسڕیتەوە',
        'user_deleted' => 'بەکارهێنەر بەسەرکەوتوویی سڕایەوە',
        'user_promoted' => 'بەکارهێنەر بەرزبەرز کرایەوە بۆ بەڕێوەبەر',
        'user_demoted' => 'بەکارهێنەر داخرایەوە بۆ بەکارهێنەری ئاسایی',
        'confirm_delete_user' => 'دڵنیایت دەتەوێت ئەم بەکارهێنەرە بسڕیتەوە؟',
        'you_cannot_modify_yourself' => 'ناتوانیت ڕۆڵی خۆت بگۆڕیت',
        'manage_items_desc' => 'زیادکردن، دەستکاری کردن، یان سڕینەوەی خزمەتگوزاری و پاکەتەکان',
        'add_new_item' => 'شتێکی نوێ زیاد بکە',
        'edit_item' => 'شت دەستکاری بکە',
        'title' => 'ناونیشان',
        'price' => 'نرخ',
        'category' => 'هاوپۆل',
        'icon' => 'ئایکۆن',
        'select_category' => 'هاوپۆل هەڵبژێرە...',
        'is_bundle' => 'پاکەتە؟',
        'item_added' => 'شت بەسەرکەوتوویی زیاد کرا',
        'item_updated' => 'شت بەسەرکەوتوویی نوێ کرایەوە',
        'item_deleted' => 'شت بەسەرکەوتوویی سڕایەوە',
        'select_icon' => 'ئایکۆن هەڵبژێرە',
        
        // Theme
        'bride' => 'کچە شهيان',
        'groom' => 'کورێ شهيان',
        'copyright' => '© 2024 پلاندانانی شهيان. خەونەکانت دەکەین بۆ ڕاست.',
    ],
];

function getCurrentLang(){
    return isset($_COOKIE['wedding_lang']) ? $_COOKIE['wedding_lang'] : 'ku';
}

function isRTL(){
    $rtlLangs = ['ar', 'ku'];
    return in_array(getCurrentLang(), $rtlLangs, true);
}

function t($key){
    global $translations;
    $lang = getCurrentLang();
    return $translations[$lang][$key] ?? $key;
}

function getDir(){
    return isRTL() ? 'rtl' : 'ltr';
}